import { Router } from 'express';
import mongoose from 'mongoose';
import Ticket from '../models/Ticket.js';
import Message from '../models/Message.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { triageTicketInBackground } from '../services/aiTriage.js';
import { emitNewMessage, emitTicketUpdate } from '../sockets/index.js';

const router = Router();

// Fixed workflow order — forward one step at a time, no skipping.
const STATUS_ORDER = ['New', 'Assigned', 'In Progress', 'Resolved'];
const STATUS_INDEX = new Map(STATUS_ORDER.map((s, i) => [s, i]));

// Fixed priority enum (same levels the AI path coerces into).
const PRIORITIES = ['Low', 'Medium', 'High'];

// Every ticket route requires a valid token.
router.use(requireAuth);

// Convenience accessors for the io handle set by index.js.
const getIo = (req) => req.app.get('io');
function emitUpdate(req, ticket) {
  const io = getIo(req);
  if (io) emitTicketUpdate(io, ticket._id, ticket.toJSON());
}

/**
 * POST /api/tickets  (customer only)
 * body: { subject, description, category? } — category is optional.
 * customerId ALWAYS comes from the token; status starts "New";
 * ticketNumber is auto-generated by the model hook.
 */
router.post('/', requireRole('customer'), async (req, res, next) => {
  try {
    const { subject, description, category } = req.body ?? {};

    if (typeof subject !== 'string' || !subject.trim() || typeof description !== 'string' || !description.trim()) {
      return res.status(400).json({ message: 'subject and description are required (category is optional)' });
    }

    let ticket;
    const MAX_ATTEMPTS = 3;
    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
      try {
        ticket = await Ticket.create({
          customerId: req.user.userId, // never trust a customerId from the request body
          subject: subject.trim(),
          description: description.trim(),
          category: typeof category === 'string' && category.trim() ? category.trim() : null,
          // status defaults to "New"; ticketNumber generated by pre('validate') hook
        });
        break;
      } catch (err) {
        // Extremely unlikely (generation is atomic), but if another concurrent
        // create won the race for a ticket number, retry with the next one
        // instead of failing the customer's request.
        const isDup = err && err.code === 11000 && /ticketNumber/.test(err.message || '');
        if (isDup && attempt < MAX_ATTEMPTS) continue;
        throw err;
      }
    }

    res.status(201).json({ ticket: ticket.toJSON() });

    // Fire-and-forget AI triage — runs AFTER the response is sent, so it can
    // never block, delay, or fail ticket creation. Writes ONLY aiSuggestion.
    triageTicketInBackground(ticket._id, ticket.subject, ticket.description);
  } catch (err) {
    next(err);
  }
});

/**
 * GET /api/tickets/mine  (customer only)
 * Returns ONLY tickets where customerId === req.user.userId.
 * NOTE: registered before /:id so "mine" is never treated as an id.
 */
router.get('/mine', requireRole('customer'), async (req, res, next) => {
  try {
    const tickets = await Ticket.find({ customerId: req.user.userId }).sort({ createdAt: -1 });
    res.json({ tickets });
  } catch (err) {
    next(err);
  }
});

/**
 * GET /api/tickets/queue  (agent only)
 * Work queue: unassigned "New" tickets (claimable) + tickets assigned to me.
 * Registered before /:id like /mine.
 */
router.get('/queue', requireRole('agent'), async (req, res, next) => {
  try {
    const tickets = await Ticket.find({
      $or: [{ assignedAgentId: req.user.userId }, { assignedAgentId: null, status: 'New' }],
    }).sort({ createdAt: 1 });
    res.json({ tickets });
  } catch (err) {
    next(err);
  }
});

/**
 * GET /api/tickets/:id  (any authenticated user, under strict rules)
 * customer: only their own ticket. agent: only tickets assigned to them,
 * or unassigned tickets still in "New". 403 (not an empty object) otherwise.
 */
router.get('/:id', async (req, res, next) => {
  try {
    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ message: 'Ticket not found' });
    }
    const ticket = await Ticket.findById(req.params.id);
    if (!ticket) {
      return res.status(404).json({ message: 'Ticket not found' });
    }

    const { role, userId } = req.user;

    if (role === 'customer') {
      if (String(ticket.customerId) !== userId) {
        return res.status(403).json({ message: 'You can only view your own tickets' });
      }
    } else if (role === 'agent') {
      const isAssignedToMe = !!ticket.assignedAgentId && String(ticket.assignedAgentId) === userId;
      const isUnassignedNew = !ticket.assignedAgentId && ticket.status === 'New';
      if (!isAssignedToMe && !isUnassignedNew) {
        return res.status(403).json({
          message: 'Agents can only view tickets assigned to them (or unassigned tickets in "New")',
        });
      }
    } else {
      return res.status(403).json({ message: 'Forbidden' });
    }

    res.json({ ticket: ticket.toJSON() });
  } catch (err) {
    next(err);
  }
});

/**
 * POST /api/tickets/:id/assign  (agent only)
 * Claim an unassigned "New" ticket: sets status to "Assigned" and assigns to the acting agent.
 */
router.post('/:id/assign', requireRole('agent'), async (req, res, next) => {
  try {
    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ message: 'Ticket not found' });
    }
    const ticket = await Ticket.findById(req.params.id);
    if (!ticket) {
      return res.status(404).json({ message: 'Ticket not found' });
    }

    if (ticket.assignedAgentId) {
      return res.status(409).json({ message: 'This ticket is already assigned to an agent' });
    }

    if (ticket.status !== 'New') {
      return res.status(400).json({ message: 'Only unassigned "New" tickets can be claimed' });
    }

    ticket.status = 'Assigned';
    ticket.assignedAgentId = req.user.userId;
    await ticket.save();
    emitUpdate(req, ticket);
    res.json({ ticket: ticket.toJSON() });
  } catch (err) {
    next(err);
  }
});

/**
 * PATCH /api/tickets/:id/status  (agent only, assigned agent only)
 * Strict state machine: New -> Assigned -> In Progress -> Resolved.
 * - exactly one forward step; skipping is rejected
 * - "Resolved" requires a non-empty resolutionNote (server-side rule)
 * - a Resolved ticket is frozen here; only POST /:id/reopen may change it
 * New -> Assigned is the "claim" step: the acting agent becomes the assignee
 * (otherwise an unassigned ticket could never leave "New").
 */
router.patch('/:id/status', requireRole('agent'), async (req, res, next) => {
  try {
    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ message: 'Ticket not found' });
    }
    const ticket = await Ticket.findById(req.params.id);
    if (!ticket) {
      return res.status(404).json({ message: 'Ticket not found' });
    }

    if (ticket.assignedAgentId && String(ticket.assignedAgentId) !== req.user.userId) {
      return res.status(403).json({ message: 'Only the assigned agent can update this ticket' });
    }

    const { status: target, resolutionNote } = req.body ?? {};
    if (typeof target !== 'string' || !STATUS_INDEX.has(target)) {
      return res.status(400).json({ message: `target status must be one of: ${STATUS_ORDER.join(', ')}` });
    }

    // HARD RULE: Resolved tickets are frozen on this route.
    if (ticket.status === 'Resolved') {
      return res.status(409).json({
        message: 'This ticket is Resolved and can no longer be changed here. Use POST /api/tickets/:id/reopen instead.',
      });
    }

    if (target === ticket.status) {
      return res.status(400).json({ message: `Ticket is already "${target}"` });
    }

    // HARD RULE: forward one step only.
    const from = STATUS_INDEX.get(ticket.status);
    const to = STATUS_INDEX.get(target);
    if (to !== from + 1) {
      return res.status(400).json({
        message: `Invalid transition ${ticket.status} -> ${target}. Only single forward steps are allowed: ${STATUS_ORDER.join(' -> ')}.`,
      });
    }

    // HARD RULE: Resolved requires a non-empty note — enforced here, server-side.
    if (target === 'Resolved') {
      const note = typeof resolutionNote === 'string' ? resolutionNote.trim() : '';
      if (!note) {
        return res.status(400).json({ message: 'A non-empty resolutionNote is required to mark a ticket Resolved.' });
      }
      ticket.resolutionNote = note;
    }

    // Claim step: New -> Assigned assigns the acting agent.
    if (ticket.status === 'New' && target === 'Assigned') {
      ticket.assignedAgentId = req.user.userId;
    }

        ticket.status = target;
    await ticket.save();
    const io = getIo(req);
    if (io) emitTicketUpdate(io, ticket._id, ticket.toJSON());
    res.json({ ticket: ticket.toJSON() });
  } catch (err) {
    next(err);
  }
});

/**
 * PATCH /api/tickets/:id/triage  (agent only, assigned agent — or an agent
 * claiming an unassigned ticket). The ONLY endpoint allowed to write the
 * ticket's REAL category and priority fields. Human input: strict enum,
 * NO coercion here (unlike the AI path). Works with or without aiSuggestion,
 * so manual triage always works even when the AI failed.
 */
router.patch('/:id/triage', requireRole('agent'), async (req, res, next) => {
  try {
    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ message: 'Ticket not found' });
    }
    const ticket = await Ticket.findById(req.params.id);
    if (!ticket) {
      return res.status(404).json({ message: 'Ticket not found' });
    }

    if (ticket.assignedAgentId && String(ticket.assignedAgentId) !== req.user.userId) {
      return res.status(403).json({ message: 'Only the assigned agent can triage this ticket' });
    }

    if (ticket.status === 'Resolved') {
      return res.status(409).json({ message: 'This ticket is Resolved. Reopen it before changing triage.' });
    }

    const { category, priority } = req.body ?? {};
    const trimmedCategory = typeof category === 'string' ? category.trim() : '';
    if (!trimmedCategory) {
      return res.status(400).json({ message: 'category is required (non-empty string)' });
    }

    // Human submitted directly: strict enum match, no silent coercion.
    if (typeof priority !== 'string' || !PRIORITIES.includes(priority)) {
      return res.status(400).json({
        message: 'priority must be exactly one of: Low, Medium, High (no coercion on this endpoint)',
      });
    }

    // Claiming: an unassigned ticket becomes the triaging agent's.
    if (!ticket.assignedAgentId) {
      ticket.assignedAgentId = req.user.userId;
    }

    ticket.category = trimmedCategory;
    ticket.priority = priority;
    await ticket.save();
    emitUpdate(req, ticket);
    res.json({ ticket: ticket.toJSON() });
  } catch (err) {
    next(err);
  }
});

/**
 * POST /api/tickets/:id/reopen  (agent only, assigned agent only)
 * The ONLY way to change a Resolved ticket: back to "In Progress",
 * resolutionNote cleared.
 */
router.post('/:id/reopen', requireRole('agent'), async (req, res, next) => {
  try {
    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ message: 'Ticket not found' });
    }
    const ticket = await Ticket.findById(req.params.id);
    if (!ticket) {
      return res.status(404).json({ message: 'Ticket not found' });
    }

    if (ticket.assignedAgentId && String(ticket.assignedAgentId) !== req.user.userId) {
      return res.status(403).json({ message: 'Only the assigned agent can reopen this ticket' });
    }

    if (ticket.status !== 'Resolved') {
      return res.status(400).json({ message: `Only Resolved tickets can be reopened (current status: "${ticket.status}")` });
    }

    ticket.status = 'In Progress';
    ticket.resolutionNote = null;
    await ticket.save();
    emitUpdate(req, ticket);
    res.json({ ticket: ticket.toJSON() });
  } catch (err) {
    next(err);
  }
});

/**
 * POST /api/tickets/:id/messages
 * Allowed for the ticket's customer OR its assigned agent only.
 * 403 for anyone else (including other agents).
 */
router.post('/:id/messages', async (req, res, next) => {
  try {
    console.log('[messages] POST /:id/messages - req.params.id:', req.params.id);
    console.log('[messages] req.user:', req.user);
    console.log('[messages] req.body:', req.body);

    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ message: 'Ticket not found' });
    }
    const ticket = await Ticket.findById(req.params.id);
    if (!ticket) {
      return res.status(404).json({ message: 'Ticket not found' });
    }

    const { role, userId } = req.user;
    const isCustomer = role === 'customer' && String(ticket.customerId) === userId;
    const isAssignedAgent =
      role === 'agent' &&
      !!ticket.assignedAgentId &&
      String(ticket.assignedAgentId) === userId;

    console.log('[messages] isCustomer:', isCustomer, 'isAssignedAgent:', isAssignedAgent);
    console.log('[messages] ticket.customerId:', ticket.customerId, 'ticket.assignedAgentId:', ticket.assignedAgentId);

    if (!isCustomer && !isAssignedAgent) {
      return res.status(403).json({ message: 'You are not authorized to message this ticket' });
    }

    const { body } = req.body ?? {};
    if (typeof body !== 'string' || !body.trim()) {
      return res.status(400).json({ message: 'Message body is required' });
    }

    console.log('[messages] Creating message...');
    const message = await Message.create({
      ticketId: ticket._id,
      senderId: req.user.userId,
      senderRole: role,
      body: body.trim(),
    });
    console.log('[messages] Message created:', message._id);

    // Live update: push the new message to everyone watching this ticket.
    const io = getIo(req);
    if (io) emitNewMessage(io, String(ticket._id), message.toJSON());

    res.status(201).json({ message: message.toJSON() });
  } catch (err) {
    console.error('[messages] Error creating message:', err);
    next(err);
  }
});

/**
 * GET /api/tickets/:id/messages
 * Same access rule as POST: ticket's customer or assigned agent only.
 * Returns the full message history ordered oldest to newest, read from
 * the database every single time (no in-memory caching between requests).
 */
router.get('/:id/messages', async (req, res, next) => {
  try {
    if (!mongoose.isValidObjectId(req.params.id)) {
      return res.status(404).json({ message: 'Ticket not found' });
    }
    const ticket = await Ticket.findById(req.params.id);
    if (!ticket) {
      return res.status(404).json({ message: 'Ticket not found' });
    }

    const { role, userId } = req.user;
    const isCustomer = role === 'customer' && String(ticket.customerId) === userId;
    const isAssignedAgent =
      role === 'agent' &&
      !!ticket.assignedAgentId &&
      String(ticket.assignedAgentId) === userId;

    if (!isCustomer && !isAssignedAgent) {
      return res.status(403).json({ message: 'You are not authorized to view messages for this ticket' });
    }

    const messages = await Message.find({ ticketId: ticket._id }).sort({ createdAt: 1 });
    res.json({ messages });
  } catch (err) {
    next(err);
  }
});

export default router;